name: Updating works remainder

on:
  schedule:
    - cron: '0 1 * */3 *'

jobs:
  stuff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/WORKS_ISSUE_TEMPLATE.md
